#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

start_service() {
	local enabled interface poll_ms udp_port

	config_load mtkcsi
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get interface main interface 'phy1-ap0'
	config_get poll_ms main poll_ms '100'
	config_get udp_port main udp_port '8888'

	procd_open_instance
	procd_set_param command /usr/sbin/mtkcsi-dump "$interface" "$poll_ms" "$udp_port"
	procd_set_param respawn 3600 5 3
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger mtkcsi
}
